#cloud-config
package_update: true
package_upgrade: true

ssh_import_id:
- gh:mozodev
ssh_keys:
  rsa_private: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----

write_files:
- path: /root/.env
  content: |
    GO_VERSION=1.21.0
    NODE_VERSION=16

runcmd:
- curl -sSL https://l.mozo.kr/up/bootstrap | bash
# LANG
- curl -sSL https://l.mozo.kr/up/node | bash
- curl -sSL https://l.mozo.kr/up/go | bash
# APP
- curl -sSL https://l.mozo.kr/up/hugo | bash

final_message: "The system is finally up, after $UPTIME seconds"
