#cloud-config
package_update: true
package_upgrade: true
ssh_import_id:
  - gh:mozodev
runcmd:
  - |
    cat << 'EOF' >> /root/.env
    GO_VERSION=1.17.0
    NODE_VERSION=16
    EOF
  # boostrap
  - curl -sSL https://git.io/J3yLS | bash
  # LANG:nodejs
  - curl -sSL https://git.io/J3MoH | bash
  # LANG:goenv
  - curl -sSL https://git.io/JuMfR | bash
  # APP:hugo
  - curl -sSL https://git.io/Jnt2g | bash
