#cloud-config
package_update: true
package_upgrade: true

ssh_import_id:
- gh:mozodev
ssh_keys:
  rsa_private: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----

write_files:
- path: /root/.env
  content: |
    PHP_VERSION=8.1
    PHP_ENV=dev
    MARIADB_VERSION=11.2

runcmd:
- curl -sSL https://l.mozo.kr/up/bootstrap | bash
- curl -sSL https://l.mozo.kr/up/php | bash
- curl -sSL https://l.mozo.kr/up/node | bash
- curl -sSL https://l.mozo.kr/up/mariadb | bash

final_message: "The system is finally up, after $UPTIME seconds"
