#cloud-config
package_update: true
package_upgrade: true

ssh_import_id:
- gh:mozodev
ssh_keys:
  rsa_private: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----

write_files:
- path: /root/.env
  content: |
    PHP_VERSION=8.1
    PHP_ENV=dev
    MARIADB_VERSION=10.7

runcmd:
# bootstrap
- curl -sSL https://git.io/J3yLS | bash
# LANG:php
- curl -sSL https://git.io/J3MVp | bash
# LANG:nodejs
- curl -sSL https://git.io/J3MoH | bash
# DB:mariadb
- curl -sSL https://git.io/J3MKe | bash

final_message: "The system is finally up, after $UPTIME seconds"
