#cloud-config
package_update: true
package_upgrade: true
ssh_import_id:
- gh:mozodev
write_files:
- path: /root/.env
  content: |
    RUBY_VERSION=3.3.7
    RAILS_QUEUE=true
    RAILS_DB=postgresql
runcmd:
- curl -sSL https://l.mozo.kr/up/bootstrap | bash
- curl -sSL https://l.mozo.kr/up/node | bash
- curl -sSL https://l.mozo.kr/up/ruby | bash
- curl -sSL https://l.mozo.kr/up/rails | bash
- curl -sSL https://l.mozo.kr/up/rclone | bash
- curl -sSL https://l.moco.kr/up/cfld | bash

final_message: "The system is finally up, after $UPTIME seconds"
