#cloud-config
package_update: true
package_upgrade: true

ssh_import_id:
  - gh:mozodev
ssh_keys:
  rsa_private: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----

write_files:
- path: /root/.env
  content: |
    RUBY_VERSION=3.0.3
    PSQL_USER=rails
    PSQL_USER_PASS=rails
    PSQL_DATABASE=rails
    RAILS_QUEUE=true
    RAILS_DB=postgresql

runcmd:
- curl -sSL https://l.mozo.kr/up/bootstrap | bash
- curl -sSL https://l.mozo.kr/up/node | bash
- curl -sSL https://l.mozo.kr/up/ruby | bash
- curl -sSL https://l.mozo.kr/up/postgres | bash
- curl -sSL https://l.mozo.kr/up/rails | bash
- curl -sSL https://l.mozo.kr/up/rclone | bash

final_message: "The system is finally up, after $UPTIME seconds"
